apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: venkateshvgs/backend-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "usermgmtdb.cgvws02g0l7w.us-east-1.rds.amazonaws.com"
        - name: DB_USER
          value: "dbadmin"
        - name: DB_PASSWORD
          value: "Kavyasree2024"
        - name: DB_NAME
          value: "usermgmtdb"
        readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
        resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # or NodePort for testing
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---


