replicaCount: 1
image:
  repository: 900840136277.dkr.ecr.us-east-1.amazonaws.com/backend
  tag: "43" # CI bumps THIS line via yq (github.run_number)
  pullPolicy: IfNotPresent
service:
  type: ClusterIP # ALB targets pods directly, so ClusterIP - never LoadBalancer
  port: 5000
containerPort: 5000
env:
  DB_HOST: "mysql"
  DB_NAME: "usermgmtdb"
  DB_USER: ""
  DB_PASSWORD: ""
secrets:
  existingSecret: "backend-secret"
database:
  serviceName: mysql
  externalName: "usermgmtdb.cgvws02g0l7w.us-east-1.rds.amazonaws.com"
probes:
#  path: /healthz
# port: 5000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
ingress:
  enabled: true
  groupName: studentmgmt
  groupOrder: 10 # backend before frontend catch-all
  scheme: internet-facing
  path: /api
  healthcheckPath: /healthz